import type { Metadata } from "next";
import "@/src/app/styles/globals.css";
import { Header } from "@/src/widgets/header";
import { Footer } from "@/src/widgets/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
